### ISSUE TITLE
Uses `sb-vm::make-ea` which has been removed

### ISSUE THREAD

**Issue by Aksej** [vydd/sketch#39]
Sketch currently does not compile on SBCL 2.1.*, since in 2.1.0 `sb-vm::make-ea` has been removed.

**Comment by Gleefre** [comment]
This is because of an outdated package (most probably `sb-cga`); which is probably due to an outdated quicklisp distribution. (See https://github.com/nikodemus/sb-cga/issues/10 for example.) If you are using quicklisp, updating it via `(ql:update-all-dists)` probably will fix the issue.

I can confirm that `sketch` can be loaded fine on SBCL 2.1.*, linux. (Tested on `sbcl-2.1.0`, `sbcl-2.1.5` and `sbcl-2.1.10`.)
